---
- name: Instalar e configurar o NTP no Oracle Linux
  hosts: oraclelinux
  remote_user: root
  tasks:
    - name: Instalar o pacote NTP
      yum:
        name: chrony
        state: present

    - name: Iniciar e habilitar o serviço NTP
      systemd:
        name: chronyd
        enabled: yes
        state: started
